import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import dynamic from 'next/dynamic';
const Webcam = dynamic(() => import('../components/webcam.js'), { ssr: false });


export default function Game() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Webcam/>
      <p>Game</p>
    </>
  );
}
