import Head from "next/head";
import styles from "@/styles/HomeScreen.module.css";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const playSound = () => {
    const audio = new Audio("/songs/buttonclick.wav"); // Ensure the sound file path is correct
    audio.currentTime = 0; // Reset the sound to start
    audio
      .play()
      .then(() => console.log("Sound played successfully"))
      .catch((error) => console.error("Audio playback failed:", error));
  };

  useEffect(() => {
    const handleKeyPress = (event) => {
      if (event.key === "Enter") {
        playSound();
        router.push("/select");
      }
    };

    // Attach the event listener when the component mounts
    window.addEventListener("keydown", handleKeyPress);

    // Cleanup the event listener when the component unmounts
    return () => {
      window.removeEventListener("keydown", handleKeyPress);
    };
  }, [router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homeScreen}>
        <h1 className={styles.title}>Dance Dance Revolution</h1>
        <p className={styles.instruction}>Press Enter to Begin</p>
      </div>
    </>
  );
}
